version: "3.7"

services:

  python:
    build: ./python
    user: dev
    volumes:
      - ${WORKSPACE_PATH}:/code

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${WORKSPACE_PATH}/.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  # apps
  simplemooc:
    build: ./python
    user: dev
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ${WORKSPACE_PATH}/simplemooc:/code
    ports:
      - "8000:8000"

  twitter-flask:
    build: ./python
    user: dev
    command: python /code/run.py
    volumes:
      - ${WORKSPACE_PATH}/twitter-flask:/code
    ports:
      - "5000:5000"